language: python
python:
  - "3.6"
dist: xenial
sudo: false

branches:
  only:
    - master

install:
  - pip install jupyter-book

# command to run tests
script:
  - make clean
  - make book

cache:
  pip: true


deploy:
  provider: pages
  target-branch: web
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master
