language: python
python:
  - "3.6"
dist: xenial
sudo: false
# command to install dependencies

#virtualenv:
#  system_site_packages: true


install:
  - pip install jupyter-book
#  - pip install -r requirements.txt
# command to run tests
script:
  - make clean
  - make book

cache:
  pip: true
#  directories:
#    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
#    - $HOME/.cache/matplotlib

deploy:
  provider: pages
  target-branch: web
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: master
