remote_theme: alexander-heimbuch/millidocs

title: Python Note
description: Note for python learning
url: "https://liao961120.github.io/pynote" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
