baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Yongfu's Python Notes"
theme = "hugo-theme-learn"
themesdir = "."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

[params]
  description = "Yongfu's notes for Python"
  author = "Yongfu Liao"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  disableLanguageSwitchingButton = true
  themeVariant = "blue"
  #editURL = "https://github.com/liao961120/pynote/edit/master/"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fas fa-blog'></i> Blog"
identifier = "blog"
url = "https://liao961120.github.io"
weight = 9

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/liao961120/pynote"
weight = 10

